version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/webbiblioteca-backend:latest
    container_name: webbiblioteca-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost
      - SUPA_BASE_URL=${SUPA_BASE_URL}
      - SUPA_ANON_KEY=${SUPA_ANON_KEY}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    networks:
      - webbiblioteca-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${DOCKER_USER}/webbiblioteca-frontend:latest
    container_name: webbiblioteca-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: always
    networks:
      - webbiblioteca-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  webbiblioteca-network:
    driver: bridge